config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
# root "patients#home"

resources :patients

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/patients_controller.rb
class PatientsController < ActionController::Base

    def index
        @patient = Patient.all  
    end


    def show
        @patient = Patient.find(params[:id])
    end

    def new
        @patient = Patient.new
    end

    def create
        Patient.create(params.require(:patient).permit(:first_name, :last_name, :diagnosis, :born_on))
    
        redirect_to authors_path
    end

    def edit
        @patient = Patient.find(params[:id])
    end

    def update
        @patient = Patient.find(params[:id])
        @patient.update(params.require(:patient).permit(:first_name, :last_name, :diagnosis, :born_on))
    
        redirect_to @patient
    end

    def destroy
        @patient = Patient.find(params[:id])
        @patient.destroy
        redirect_to patients_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HospitalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for @patient do |f| %>
    <div class="field">
        <%= f.label :first_name, "First Name" %>
        <%= f.text_field :first_name %>
    </div>


    <div class="field">
        <%= f.label :last_name, "Last Name" %>
        <%= f.text_field :last_name %>
    </div>

    <div class="field">
        <%= f.label :born_on, "Date of Birth" %>
        <%= f.text_field :born_on %>
    </div>

    <div class="field">
        <%= f.label :diagnosis, "Diagnosis" %>
        <%= f.text_field :diagnosis %>
    </div>

    <%= f.submit "Submit", :class => 'button' %>
<% end %>

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>

<%= render "form" %>

app/views/patients/index.html.erb
<h1>All Patients</h1>

<h1> <%= link_to 'Create a New Patient', new_patient_path %> </h1>

<% @patient.each do |patient| %>
  <h1> <%= link_to "#{patient.first_name}  #{patient.last_name}", patient_path(patient)%> </h1>
  
<% end %>

app/views/patients/new.html.erb
<h1>Create a New Patient</h1>

<%= render "form" %>

app/views/patients/show.html.erb
<h1> <%= "#{@patient.first_name}  #{@patient.last_name}"%>'s Page</h1>

<h3> <%= @patient.born_on %></h3>
<h5> <%= @patient.diagnosis %></h5>

<h3> <%= link_to "Edit Patient", edit_patient_path(@patient) %></h3>

<h3> <%= link_to "Delete Patient", patient_path(@patient),
                data: { 
                        turbo_method: :delete, 
                        turbo_confirm: "Are you sure you want to delete #{@patient.first_name}"
                        } %></h3>

<h3> <%= link_to "Back to Patients?", patients_path%></h3>